// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxzamhu2p3ivQPclhYsrme_pBGhcydCJQ',
    appId: '1:61493811573:web:5af15aefef5afb73d85b3c',
    messagingSenderId: '61493811573',
    projectId: 'roadna-ce6a0',
    authDomain: 'roadna-ce6a0.firebaseapp.com',
    databaseURL: 'https://roadna-ce6a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'roadna-ce6a0.firebasestorage.app',
    measurementId: 'G-DD849SH381',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW3TXSc-nEgiHyo40T3qTehX5u6lM_nvg',
    appId: '1:61493811573:android:e4bf58896b4a0c04d85b3c',
    messagingSenderId: '61493811573',
    projectId: 'roadna-ce6a0',
    databaseURL: 'https://roadna-ce6a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'roadna-ce6a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhkRGyL6-tvw8Hz0KK8JW9LQEOL_gPro',
    appId: '1:61493811573:ios:f81045748208f356d85b3c',
    messagingSenderId: '61493811573',
    projectId: 'roadna-ce6a0',
    databaseURL: 'https://roadna-ce6a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'roadna-ce6a0.firebasestorage.app',
    iosBundleId: 'com.example.smartcityy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdhkRGyL6-tvw8Hz0KK8JW9LQEOL_gPro',
    appId: '1:61493811573:ios:f81045748208f356d85b3c',
    messagingSenderId: '61493811573',
    projectId: 'roadna-ce6a0',
    databaseURL: 'https://roadna-ce6a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'roadna-ce6a0.firebasestorage.app',
    iosBundleId: 'com.example.smartcityy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxzamhu2p3ivQPclhYsrme_pBGhcydCJQ',
    appId: '1:61493811573:web:af3585e8289a433ad85b3c',
    messagingSenderId: '61493811573',
    projectId: 'roadna-ce6a0',
    authDomain: 'roadna-ce6a0.firebaseapp.com',
    databaseURL: 'https://roadna-ce6a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'roadna-ce6a0.firebasestorage.app',
    measurementId: 'G-E61DMJBE6L',
  );

}